### ISSUE TITLE
"Stable Diffusion weights file" step needs double quotes in ZSH

### ISSUE THREAD

**Issue by jayKlo** [joelparkerhenderson/stable-diffusion-macos-install-help#1]
If using the default zsh for MacOS the "Stable Diffusion weights file" curl command step will fail with "no matches found" error. Adding double quotes around the url resolves the issue. Issue does not occur when using bash.

**Comment by joelparkerhenderson** [comment]
Thank you. I'll fix it right now.

**Comment by jayKlo** [comment]
Thank you for the quick update and for the guide--worked flawlessly.
