### ISSUE TITLE
Can't create conda enviroment

### ISSUE THREAD

**Issue by pgilfernandez** [joelparkerhenderson/stable-diffusion-macos-install-help#3]
Hi Joel,

Thanks for the nice tutorial.
I got stuck at the line:
```
CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yaml
```
as it says:
```
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: libuci
  channel url: https://conda.anaconda.org/libuci
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```
My channels are:
  - conda-forge
  - libuci
  - oce
  - boost
  - pivy
  - coin
  - freecad
  - defaults
  - looooo
  - dlr-sc
  - spyder-ide

Buy I don't know what channels should I have... BTW the problem seems to be with libuci... is it necessary?

Thanks

**Comment by joelparkerhenderson** [comment]
Thanks, I'll take a look today.

**Comment by joelparkerhenderson** [comment]
I did some research. Is it possible that you have a different installation of Anaconda or equivalent? 

Can you try these diagnostic commands and  copy/paste the output? You may want to omit anything private in the output, such as your username, or machine name, etc.

```sh
% conda info
% which conda
% conda --version
% more ~/.condarc
```

On my MacBook Pro M1 Monterey, Anaconda installs itself without any channels, and doesn't use any dot file `~/.condarc`. 

I don't know (yet) why your installation has channels.

When I look for the channel `libuci`, it doesn't seem to exist on the conda site.

You can try removing the channel like this:

```sh
conda config --remove channels 'https://conda.anaconda.org/libuci'
```

You can add the channel again, if you ever want to, like this:

```sh
conda config --add channels 'https://conda.anaconda.org/libuci'
```

**Comment by joelparkerhenderson** [comment]
I haven't heard back from you in two weeks, so I'll close this issue for now. Feel free to reopen it if you want.
