### ISSUE TITLE
Anaconda installation script

### ISSUE THREAD

**Issue by pgilfernandez** [joelparkerhenderson/stable-diffusion-macos-install-help#4]
Following your tutorial I found the line:
```
% sudo /opt/homebrew/Caskroom/anaconda/2022.05/Anaconda3-2022.05-MacOSX-arm64.sh
```
Needed an additional ```sh``` in order to run the script, that is:
```
% sudo sh /opt/homebrew/Caskroom/anaconda/2022.05/Anaconda3-2022.05-MacOSX-arm64.sh
```
It also would be nice to point out that the name of the script might change with futures updates...

Cheers

**Comment by joelparkerhenderson** [comment]
That's interesting-- the line doesn't need the `sh` on my system. I'll take a look today.

For the naming, you're 100% right, and I'll add that to the tutorial today. Thanks!

**Comment by joelparkerhenderson** [comment]
Today I added this new info, thanks to you. I believe this solves your issue, yes?


Anaconda uses an installation shell script that you must run.

Find the script:

```sh
find /opt/homebrew/Caskroom/anaconda -name "*.sh" 
```

Output shows the shell script name, which may use different version numbers depending on when you install Anaconda:

```sh
/opt/homebrew/Caskroom/anaconda/2022.05/Anaconda3-2022.05-MacOSX-arm64.sh
```

Run the shell script via `sudo` and `sh` and the script name from above:

```sh
% sudo sh /opt/homebrew/Caskroom/anaconda/2022.05/Anaconda3-2022.05-MacOSX-arm64.sh
```

Your system should prompt you to type your password, then should run the shell script.

**Comment by pgilfernandez** [comment]
Yes
=)
